FROM node:15.1.0-alpine as build

WORKDIR /lmrdashboard/frontend
COPY . .

ARG LMR_EVENT_SOURCE="http://localhost:4000/test"
ENV LMR_EVENT_SOURCE=$LMR_EVENT_SOURCE

RUN yarn install
RUN npx next telemetry disable
RUN yarn export

FROM nginx

WORKDIR /usr/share/nginx/html
COPY --from=build /lmrdashboard/frontend/out .
